### ISSUE TITLE
BLOQUEO DE OPCIONES DE PAGO

### ISSUE THREAD

**Issue by Leous88** [TransbankDevelopers/transbank-plugin-prestashop-onepay#21]
Al activar modulo de ONEPAY en prestashop 1.7.... el modulo ONEPAY no deja seleccionar otros medios de pago, ya sean los nativos u otras opciones disponibles en el paso de pagos. 

esto ocurre desde el lanzamiento de onepay y no ha sido resuelto en ninguna version posterior, pueden hacer las pruebas en cualquier instalacion nueva o en uso de prestashop 1.7 en adelante. e intentar otro medio de pago que no sea onepay. 

al desactivar el modulo desde el backoffice la web queda operativa en su totalidad.

**Comment by a1b4** [comment]
@Leous88 Hola, pudiste solucionar este tema?

saludos.

**Comment by Leous88** [comment]
si, gracias. desde transbank resolvieron el bug de Onepay. lo actualizaron y resolvieron. ahora funciona bien (hace un tiempo ya). Gracias

Changelog
Todos los cambios notables a este proyecto serán documentados en este archivo.

El formato está basado en Keep a Changelog y este proyecto adhiere a Semantic Versioning.

[1.0.9] - 2018-12-10
Fixed
Corrige bloqueo de otros medios de pago existentes cuando se activa el de Onepay.
Added
Agrega soporte para Prestashop 1.6.

**Comment by a1b4** [comment]
Perfecto, muchas gracias.
